name: Add a publication
description: Contribute a paper to this project
title: "[Paper Contribution]: "
labels: ["Paper"]
assignees:
  - gOATiful
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute to this project!
  - type: input
    id: title
    attributes:
      label: BibTex entry
      description: "Enter the corresponding BibTex entry for the publication you want to add"
    validations:
      required: true
  - type: textarea
    id: artifacts
    attributes:
      label: Artifacts
      description: "Enter the artifact urls here (new line for each artifact url)"
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: "For which tasks are the model(s) used in the work (new line for each task)"
    validations:
      required: true
  - type: textarea
    id: models
    attributes:
      label: Models
      description: "Which models are used in the paper? (new line for each model)"
    validations:
      required: true
    
